Finish ansible for non docker version

diff --git a/ansible/deploy_regular_node.yml b/ansible/deploy_regular_node.yml
--- a/ansible/deploy_regular_node.yml
+++ b/ansible/deploy_regular_node.yml
@@ -1,15 +1,15 @@
 ---
 
 - hosts: all
-  remote_user: '{{ remote_user }}'
+  remote_user: {{ remote_user|quote }}
   environment:
-    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
+    PATH: /usr/local/go/bin:{{ ansible_env.PATH|quote }}
 
   tasks:
     - name: Add the deploy user
       become: yes
       user:
-        name: '{{ deploy_user }}'
+        name: {{ deploy_user|quote }}
         state: present
     
     - name: Install dependencies
@@ -42,7 +42,7 @@
     - name: Install Golang compiler
       become: yes
       unarchive:
-        src: https://storage.googleapis.com/golang/'{{ golang_version }}'
+        src: https://storage.googleapis.com/golang/{{ golang_version|quote }}
         dest: /usr/local/
         remote_src: yes
 
@@ -53,7 +53,7 @@
           git:
             repo: https://github.com/ConsenSys/quorum.git
             dest: /tmp/quorum
-            version: '{{ quorum_version }}'
+            version: {{ quorum_version|quote }}
         - name: Execute make command
           shell: make -C /tmp/quorum all
         - name: Copy geth to right location
@@ -72,7 +72,7 @@
 
     - name: Initialize the node if necessary
       become: yes
-      become_user: '{{ deploy_user }}'
+      become_user: {{ deploy_user|quote }}
       when: not INITIALIZED.stat.exists
       block:
         - name: Create the data directory if it does not exist yet
@@ -88,7 +88,7 @@
 
         - name: Download genesis.json
           get_url:
-            url: '{{ genesis_json_url }}'
+            url: {{ genesis_json_url|quote }}
             dest: ~/genesis.json
 
         - name: Execute geth command
@@ -99,14 +99,43 @@
 
     - name: 'Get nodes and start geth node'
       become: yes
-      become_user: '{{ deploy_user }}'
+      become_user: {{ deploy_user|quote }}
       block:
         - name: Create temporary file
           tempfile:
             path: /tmp/updatePerm.XXXXXX
           register: TMPFILE
-        - name: Create the data directory if it does not exist yet
+        - name: Get current nodes and parse databases
           shell: |
             for i in boot-nodes.json validator-nodes.json regular-nodes.json ; do
-              wget -q -O ~/env/${i} https://raw.githubusercontent.com/alastria/alastria-node/${NODE_BRANCH}/data/${i}
+              wget -q -O ~/env/${i} https://raw.githubusercontent.com/alastria/alastria-node/{{ node_branch|quote }}/data/${i}
             done
+
+            case {{ node_type|quote }} in
+              "bootnode")
+                cat ~/env/boot-nodes.json ~/env/validator-nodes.json ~/env/regular-nodes.json >> {{ TMPFILE.path|quote }}
+              ;;
+              "validator")
+                cat ~/env/boot-nodes.json ~/env/validator-nodes.json >> {{ TMPFILE.path|quote }}
+              ;;
+              "general")
+                cat ~/env/boot-nodes.json >> {{ TMPFILE.path|quote }}
+              ;;
+              *)
+                echo "ERROR: nodetype not recognized"
+                exit 1
+              ;;
+            esac
+
+            sed -e '1s/^/[\n/' -i {{ TMPFILE.path|quote }}
+            sed -e '$s/,$/\n]/' -i {{ TMPFILE.path|quote }}
+
+            cat {{ TMPFILE.path|quote }} > ~/data/static-nodes.json
+            cat {{ TMPFILE.path|quote }} > ~/data/permissioned-nodes.json
+        - name: Prepare geth and launch node
+          shell: |
+            source ~/env/geth.common.sh
+            source ~/env/geth.node.{{ node_type|quote }}.sh
+
+            export PRIVATE_CONFIG="ignore"
+            exec /usr/local/bin/geth --datadir ~/data ${GLOBAL_ARGS} ${NETSTATS_METRICS} ${INFLUX_METRICS} ${NODE_ARGS} ${LOCAL_ARGS}
